VehicleOrigin:
  vehicle_origin: 0  # 0 --- Rear Axle, 1 --- C.G.

RearToImu:
  parent_frame_id: ego_frame
  child_frame_id: imu
  transform_xyz_m: [0.0, 0.0, 0.5]
  rotation_rpy_deg: [-0.7, -1.5, -89.0]

CGToImu:
  parent_frame_id: ego_frame
  child_frame_id: imu
  transform_xyz_m: [-1.51, 0.0, 0.5]
  rotation_rpy_deg: [-0.7, -1.5, -89.0]

RearToGps:
  parent_frame_id: ego_frame
  child_frame_id: gps
  transform_xyz_m: [0.0, 0.0, 0.5]
  rotation_rpy_deg: [0.0, 0.0, 1.3]

CGToGps:
  parent_frame_id: ego_frame
  child_frame_id: gps
  transform_xyz_m: [-1.51, 0.0, 0.5]
  rotation_rpy_deg: [0.0, 0.0, 1.3]

RearToMainLiDAR:
  parent_frame_id: ego_frame
  child_frame_id: velodyne
  transform_xyz_m: [1.2, 0.0, 1.88]
  rotation_rpy_deg: [0.0, 1.0, 0.5]

CGToMainLiDAR:
  parent_frame_id: ego_frame
  child_frame_id: velodyne
  transform_xyz_m: [-0.31, 0.0, 1.88]
  rotation_rpy_deg: [0.0, 1.0, 0.5]